/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        JButton botonesD[] = {cmdManual, cmdAutomatic, cmdOperations};
        JButton botonesH[] = {cmdCreate, cmdClean};
        

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNrows = new javax.swing.JTextField();
        txtNcolumns = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTable1 = new javax.swing.JTable();
        cmbOperations = new javax.swing.JComboBox<String>();
        jPanel2 = new javax.swing.JPanel();
        cmdCreate = new javax.swing.JButton();
        cmdClean = new javax.swing.JButton();
        cmdOperations = new javax.swing.JButton();
        cmdAutomatic = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRoute = new javax.swing.JTextArea();
        cmdExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos iniciales ", 0, 0, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(51, 153, 255));
        jLabel4.setText("Numero de filas:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setText("Numero de columnas: ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtNrows.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNrowsKeyTyped(evt);
            }
        });
        jPanel3.add(txtNrows, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 30, -1));

        txtNcolumns.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNcolumnsKeyTyped(evt);
            }
        });
        jPanel3.add(txtNcolumns, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 30, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 230, 100));

        tblTable1.setBackground(new java.awt.Color(51, 51, 51));
        tblTable1.setForeground(new java.awt.Color(51, 153, 255));
        tblTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTable1.setCellSelectionEnabled(true);
        tblTable1.setEnabled(false);
        jScrollPane2.setViewportView(tblTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 410, 190));

        cmbOperations.setBackground(new java.awt.Color(51, 51, 51));
        cmbOperations.setForeground(new java.awt.Color(51, 153, 255));
        cmbOperations.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recorrido 1", "Recorrido 2", "Recorrido 3", "Recorrido 4", "Recorrido 5" }));
        jPanel1.add(cmbOperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", 0, 0, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCreate.setBackground(new java.awt.Color(204, 204, 204));
        cmdCreate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        cmdCreate.setForeground(new java.awt.Color(0, 153, 204));
        cmdCreate.setText("Crear");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });
        jPanel2.add(cmdCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        cmdClean.setBackground(new java.awt.Color(204, 204, 204));
        cmdClean.setForeground(new java.awt.Color(153, 0, 0));
        cmdClean.setText("Limpiar");
        cmdClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCleanActionPerformed(evt);
            }
        });
        jPanel2.add(cmdClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, -1));

        cmdOperations.setBackground(new java.awt.Color(204, 204, 204));
        cmdOperations.setText("Operacion");
        cmdOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperationsActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOperations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        cmdAutomatic.setBackground(new java.awt.Color(204, 204, 204));
        cmdAutomatic.setText("Automatico");
        cmdAutomatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutomaticActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAutomatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        cmdManual.setBackground(new java.awt.Color(204, 204, 204));
        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel2.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 150, 230));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Recorrido de matrices");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", 0, 0, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(0, 153, 255));

        txtRoute.setEditable(false);
        txtRoute.setBackground(new java.awt.Color(0, 0, 0));
        txtRoute.setColumns(20);
        txtRoute.setForeground(new java.awt.Color(51, 153, 255));
        txtRoute.setRows(5);
        jScrollPane1.setViewportView(txtRoute);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 650, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 680, 100));

        cmdExit.setBackground(new java.awt.Color(204, 204, 204));
        cmdExit.setText("Salir");
        cmdExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExitActionPerformed(evt);
            }
        });
        jPanel1.add(cmdExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/black-minimalistic_00416715 (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(968, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNrowsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNrowsKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNrowsKeyTyped

    private void txtNcolumnsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNcolumnsKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(evt.getKeyChar())) {
            getToolkit().beep();

            evt.consume();
        }
    }//GEN-LAST:event_txtNcolumnsKeyTyped

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        int sw;
        sw = 1;
        if (txtNrows.getText().isEmpty()) {
            Helper.mensaje(this, "Por favor digite el numero de Filas", 2);
            txtNrows.requestFocusInWindow();
            sw = 0;
        } else if (txtNcolumns.getText().isEmpty()) {
            Helper.mensaje(this, "Por favor digite el numero de Columnas", 2);
            txtNcolumns.requestFocusInWindow();
            sw = 0;
        }
        if (sw == 1) {

            int nf, nc;
            DefaultTableModel tm;
            nf = Integer.parseInt(txtNrows.getText());
            nc = Integer.parseInt(txtNcolumns.getText());

            if (nf > 15) {
                Helper.mensaje(this, "Para una correcta vizualizacion el numero de fila no debe ser mayor de 15", 2);
                txtNrows.requestFocusInWindow();
            } else if (nc > 15) {
                Helper.mensaje(this, "Para una correcta vizualizacion el numero de columnas no debe ser mayor de 15", 2);
                txtNcolumns.requestFocusInWindow();
            } else {
                tm = (DefaultTableModel) tblTable1.getModel();

                tm.setRowCount(nf);
                tm.setColumnCount(nc);

                JButton botonesH[] = {cmdManual, cmdAutomatic, cmdClean};
                JButton botonesD[] = {cmdCreate, cmdOperations};

                Helper.habilitarBotones(botonesH);
                Helper.deshabilitarBotones(botonesD);

            }
            txtNcolumns.setEditable(false);
            txtNrows.setEditable(false);
        }
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void cmdCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCleanActionPerformed
        txtNrows.setText("");
        txtNcolumns.setText("");
        txtNrows.requestFocusInWindow();
        cmbOperations.setSelectedIndex(0);
        txtRoute.setText("");

        Helper.porDefectoTabla(tblTable1);

        JButton botonesH[] = {cmdCreate, cmdClean};
        JButton botonesD[] = {cmdManual, cmdAutomatic, cmdOperations};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        txtNcolumns.setEditable(true);
        txtNrows.setEditable(true);
    }//GEN-LAST:event_cmdCleanActionPerformed

    private void cmdOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperationsActionPerformed
        int op, nf, nc;
        op = cmbOperations.getSelectedIndex();

        nf = tblTable1.getRowCount();
        nc = tblTable1.getColumnCount();
        if (nf < 5 || nc < 5) {
            Helper.mensaje(this, "Para poder hacer las operaciones el numero de columnas debes ser superior a 5", 2);
            JButton botonesH[] = {cmdClean};
            JButton botonesD[] = {cmdManual, cmdAutomatic, cmdOperations, cmdCreate};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);

        } else {
            switch (op) {

                case 0://Recorrido1-Route1
                    if (nf % 2 == 0 || nc % 2 == 0) {
                        Helper.mensaje(this, "Para poder hacer este recorrido el numero de filas y columnas deben ser impares", 2);
                    } else if (nc != nf) {
                        Helper.mensaje(this, "Para poder hacer este recorrido el numero de filas y columnas deben ser iguales",2);

                    } else {
                        txtRoute.setText(Helper.R1(tblTable1));
                    }

                    break;
                    case 1://Recorrido2-Route2
                    if (nf % 2 == 0 || nc % 2 == 0) {
                        Helper.mensaje(this, "Para poder hacer este recorrido el numero de filas y columnas deben ser impares", 2);
                    } else if (nc != nf) {
                        Helper.mensaje(this, "Para poder hacer este recorrido el numero de filas y columnas deben ser iguales",2);

                    } else {
                        txtRoute.setText(Helper.R2(tblTable1));
                    }

                    break;
                    case 2: //Recorrido3-Route3
                        
                        Helper.mensaje(this, "Este recorrido no esta disponible por ahora, estamos trabajando para su pronta normalización",2);
                        break;
                    case 3: // REcorrido4-Route4
                        if(nf!=nc){
                          Helper.mensaje(this, "Para poder hacer este recorrido el numero de filas y columnas deben ser iguales",2);   
                        }else{
                           txtRoute.setText(Helper.R4(tblTable1)); 
                        }
                        
                        break;
                        case 4: // Recorrido5-Route5
                            if(nc%2==0){
                                Helper.mensaje(this,"Para poder hacer este recorrido el numero de columnas debe ser impar",2);
                            }else{
                        txtRoute.setText(Helper.R5(tblTable1));
                        }
                        break;
            
        }
        }

    }//GEN-LAST:event_cmdOperationsActionPerformed

    private void cmdAutomaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutomaticActionPerformed
        int nf, nc, n;
        nf = tblTable1.getRowCount();
        nc = tblTable1.getColumnCount();
        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTable1.setValueAt(n, i, j);
            }

        }
        JButton botonesH[] = {cmdOperations, cmdClean};
        JButton botonesD[] = {cmdCreate, cmdManual, cmdAutomatic};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdAutomaticActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        int nf, nc;
        int n;
        int sw, res;

        nc = tblTable1.getColumnCount();
        nf = tblTable1.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elmento en la posición [" + i + "]" + "[" + j + "]").trim());
                        tblTable1.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;

                            Helper.porDefectoTabla(tblTable1);

                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[] = {cmdOperations, cmdClean};
        JButton botonesD[] = {cmdCreate, cmdManual, cmdAutomatic};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExitActionPerformed
        int sw,res;
        sw=1;
       res= JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
        if(res==0){
            sw=1;
            System.exit(0);
        }else{
            sw=0;
        }
       
        
    }//GEN-LAST:event_cmdExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperations;
    private javax.swing.JButton cmdAutomatic;
    private javax.swing.JButton cmdClean;
    private javax.swing.JButton cmdCreate;
    private javax.swing.JButton cmdExit;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdOperations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTable1;
    private javax.swing.JTextField txtNcolumns;
    private javax.swing.JTextField txtNrows;
    private javax.swing.JTextArea txtRoute;
    // End of variables declaration//GEN-END:variables
}
